### ISSUE TITLE
Method to retrieve the attributes of a type is misnamed

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/client-java#127]
## Description

On the server `Type` has method `.has()` to retrieve the `AttributeType`s it owns. For `Thing` instances, the equivalent method is named `.attributes()`, to retrieve the attribute instances it owns. However in client-java (and presumably other clients) both methods are named `.attributes()`.

**Comment by alexjpwalker** [comment]
Since the 2.0 changes the method names are now consistent with Core.

To retrieve the attribute types of a `ThingType`, use `getOwns`; to retrieve the attributes of a `Thing`, use `getHas`.
