### ISSUE TITLE
Review usages of '...' to denote an array filter in Concept methods

### ISSUE THREAD

**Issue by alexjpwalker** [graknlabs/client-java#154]
## Problem to Solve

We discovered that `Relation.players(RoleType...)` was able to accept no parameters, and it would be treated as an empty array, leading to unexpected results. We fixed this case, but there may be others that need to be looked at.

## Proposed Solution

In cases where `T...` is used to denote an array filter, refactor the relevant method into 2 methods, one with no parameters and one with `List<T>` or `List<? extends T>` as the parameter type.

**Comment by haikalpribadi** [comment]
The solution to this is to add at least ONE argument first, before putting the optional array, which would enforce a minimum of ONE argument provided. So this signature:
```
Relation.players(RoleType... roleTypes)
```
Should be:
```
Relation.players(RoleType roleType, RoleType... roleTypes)
```

Make sure the logic of that method actually DISALLOW no arguments.

**Comment by haikalpribadi** [comment]
@alexjpwalker this really shouldn't have been opened as an issue. If you did a quick "search" and check in the codebase, you would have found there were 3 methods where this issue could apply. Looking at those 3 methods, and their implementation on Grakn side took literally less than 1 minute, which I presume is faster if not relatively the same time as it would have taken to write this issue. In that one minute, you would have found that you didn't need to write this issue.

![Screenshot 2021-02-02 at 17 23 18](https://user-images.githubusercontent.com/567679/106638106-684a1380-657b-11eb-9177-2a97100efb85.png)
