### ISSUE TITLE
Core: Fix RemoteMetaType vs RemoteType

### ISSUE THREAD

**Issue by grabl** [graknlabs/client-java#17]
_This issue was originally posted by @haikalpribadi  on 2018-07-05 20:40_.

**Comment by marco-scoppetta** [comment]
@haikalpribadi I have moved this into client java as both the mentioned classes now reside in the client. Is this still relevant?

**Comment by haikalpribadi** [comment]
Yes, it's still relevant if it hasn't been implemented yet, @marco-scoppetta

**Comment by alexjpwalker** [comment]
I don't believe this issue is likely to be relevant anymore, as `MetaType` no longer exists.
