### ISSUE TITLE
Fix failing BDD tests

### ISSUE THREAD

**Issue by lriuui0x0** [graknlabs/client-java#223]
See the failing BDD tests in https://github.com/graknlabs/behaviour/pull/133 and https://github.com/graknlabs/behaviour/pull/132

**Comment by lolski** [comment]
[Triaged] @haikalpribadi placing in 2.0 production with priority medium, since the test is about verifying whether we properly guard against writing data in a schema session and vice versa. The workaround for the user is to simply be careful not do that.

**Comment by haikalpribadi** [comment]
I think all BDD test are `high`, no, @lolski ? They're actual features we need to deliver that don't work yet, right?

**Comment by haikalpribadi** [comment]
If a key feature isn't working, then (most of the time) I think you won't have a workaround.

**Comment by alexjpwalker** [comment]
Good news, both of these were fixed in https://github.com/graknlabs/client-java/pull/227/files !
