### ISSUE TITLE
client-java alpha-5: cannot get client!

### ISSUE THREAD

**Issue by hkuich** [graknlabs/client-java#241]
## Description

in docs to get a client:

```Grakn.Client client = new GraknClient("localhost:1729");```

error:

```
error: constructor GraknClient in class GraknClient cannot be applied to given types;
        Grakn.Client client = new GraknClient(this.graknURI);
                              ^
  required: no arguments
  found: String
  reason: actual and formal argument lists differ in length
```

if you give it nothing:

```Grakn.Client client = new GraknClient();```

error is:

```error: incompatible types: GraknClient cannot be converted to Client
        Grakn.Client client = new GraknClient();
```

## Environment

1. Mac OS 10
2. grakn: alpha-2, client-java: alpha-5

## Reproducible Steps

see above

**Comment by lriuui0x0** [comment]
@hkuich Yes! There's a slight API change to support our grakn cluster integration (to be released soon). Please use `GraknClient.core(this.graknURI)` to connect to client.

**Comment by hkuich** [comment]
@lriuui0x0 : fixed - also no need for ```new``` anymore... :) Thanks!

**Comment by lolski** [comment]
We'll update the docs soon!
