### ISSUE TITLE
Java Concept API method to re(set) direct supertype of a given type

### ISSUE THREAD

**Issue by sorsaffari** [graknlabs/client-java#4]
## Problem to Solve

Use the Concept API with Java to (re)set the direct supertype of a given type via one single method call.

## Current Workaround
Chain the `sup` and `label` methods: `type.sup(Type type).label(Label label);`
This in comparison with usage in clients Node.js and Python (i.e `sup(type)`) is less convinient.

## Proposed Solution

Besides `sup()`, have another method (`sup(Type type)`) that accepts the new supertype as a parameter.

## Additional Information

This feature request is to ensure consistency across our clients.

**Comment by alexjpwalker** [comment]
Now exists as `setSupertype`
