### ISSUE TITLE
Performance refactor of Answer and Concept API

### ISSUE THREAD

**Issue by adammitchelldev** [graknlabs/client-java#84]
## Problem to Solve

Currently, the Concept API is the main point of data transfer to the Grakn user. A Graql query is executed (or streamed), which results in a number of Concepts being returned (usually a list of ConceptMaps). These concepts are very simply Grakn IDs which are then used by synchronous Concept API RPCs to retrieve data and other associated concepts.

This means that all data returned from a query is actually fetched as separate concept API RPC calls, which results in a large amount of bidirectional communication and waiting. Any amount of latency introduced by the network is multiplied by the number of these RPCs, which can often be a multiple of the number of concepts retrieved by a single query.

As an example, if network latency is 10ms and 100 concepts are fetched, with 4 RPC calls per concept, 4 seconds of total latency is introduced.

It is clear that this can pose a performance issue to users who intend to build low-latency applications on Grakn.

## Current Workaround

There is currently no good workaround, other than to minimise the number of Concept API calls made (it is impossible to do asynchronous calls on a transaction currently).

A short-term fix was proposed which would simply pre-fetch common Concept API answers, but then the boundaries between RPC-driven communication and results parsing would be obfuscated. This solution would alleviate the issues but we've decided on a wider-spread refactor to deal with the issue.

## Proposed Solution

Instead of the full `Concept` API being the single point of contact for `Answer`s, the `Answer` become "Value-only" `Concepts`, as in they only expose the methods to retrieve the pre-fetched results and don't expose anything further. This makes the separation between what exists in results (and therefore doesn't require any network overhead to use) and what must be fetched or performed via RPC explicit to the user.

The way I am planning to achieve this is to simplify the current Concept interfaces down to a simple set of operations that should superset the 99% use case for queries. This will include attribute values and schema type information that will also be embedded in the answers protocol. When a user wants to use the full Concept API instead, it must construct the "live" concept from the retrieved concepts using a method and passing a transaction. For example:

```
concept.withTransaction(tx).sups()
```

This requires an API change that will break existing users of Grakn client, so we will also take the opportunity to rework the client API into an interface with a static factory method.

## Summary of required work

- [ ] Update protocol [x], server [ ] and client [ ] to allow retrieval of multiple concepts from a single RPC.
- [ ] Update protocol to include basic concepts to be used in "Answer" API.
- [ ] Update server to transmit all basic concepts for the "Answer" API.
- [ ] Update client-java with separated Concept API from "Answer" API, allowing the creation of a "live" Concept from a result concept.
- [ ] Refactor client-java API whilst we are here to avoid needing to do it again in future.

**Comment by haikalpribadi** [comment]
Implemented by https://github.com/graknlabs/client-java/pull/85
